apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: qa

patches:
  - path: patches.yaml

images:
  - name: ghcr.io/YOUR_GITHUB_USERNAME/YOUR_RAG_APP_REPO
    newTag: qa-latest
