apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

namespace: production

patches:
  - path: patches.yaml

images:
  - name: ghcr.io/ageorge2026/ml-rag-apps-one
    newTag: prod-PLACEHOLDER_SHA
