apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rag-app-qa
  namespace: automation
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: default
  source:
    repoURL: 'https://github.com/YOUR_GITHUB_USERNAME/YOUR_MANIFEST_REPO.git'
    targetRevision: HEAD
    path: overlays/qa/
  destination:
    server: 'https://kubernetes.default.svc'
    namespace: qa
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
